chat_room/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('rooms/', include('room.urls')),

]

core/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import *

app_name = 'core'

urlpatterns = [
    path('', frontpage, name='frontpage'),
    path('signup/', signup, name='signup'),
    path('login/', login_custom, name='login'),
    path('logout/', logout_custom, name='logout'),
    # path('logout/', LogoutView.as_view(), name='logout'),

]

room/urls.py
from django.urls import path

from .views import rooms, room

app_name = 'room'

urlpatterns = [
    path('', rooms, name='rooms'),
    path('room/<slug:the_slug>/', room, name='room'),

]

core/models.py
from django.db import models

# Create your models here.

room/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify


class Room(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)  # it's for the url for each room

    def save(self, *args, **kwargs):
        self.slug = self.slug or slugify(self.name)
        super().save(*args, **kwargs)


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, related_name='messages', on_delete=models.CASCADE)
    content = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('date_added',)

core/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

core/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import login, authenticate
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.views import auth_logout
from .forms import SignUpForm


def frontpage(request):
    context = {}
    return render(request, 'core/frontpage.html', context)


@csrf_exempt
def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('core:frontpage')
    else:
        form = SignUpForm()
    return render(request, 'core/signup.html', {'form': form})


def login_custom(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return redirect('core:frontpage')

    return render(request, 'core/login.html')


def logout_custom(request, ):
    auth_logout(request)
    return redirect('core:frontpage')

room/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from .models import Room, Message


@login_required(login_url='core:login')
def rooms(request):
    rooms = Room.objects.all().order_by('-id')

    context = {'rooms': rooms}
    return render(request, 'room/rooms.html', context)


@login_required(login_url='core:login')
def room(request, the_slug):
    room = Room.objects.get(slug=the_slug)
    messages = Message.objects.filter(room=room)[:30]

    context = {
    'room': room,
    'messages': messages
    }
    return render(request, 'room/room.html', context)

core/templates/core/base.html
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}{% endblock %}Chat Room App</title>

    <script src="https://cdn.tailwindcss.com"></script>

    <style>
        .chat-messages{
            height: 400px;
            overflow-y: auto;
        }
    </style>

</head>

<body class="bg-teal-600">
<nav class="flex items-center justify-between px-4 py-6 bg-teal-800">
    <div>
        <a href="/" class="text-xl text-white">Chat Room App</a>
    </div>

    <div class="flex items-center space-x-4">
        {% if request.user.is_authenticated %}
            <a href="{% url 'room:rooms' %}" class="text-white hover:text-gray-200">Rooms</a>

            <a href="{% url 'core:logout' %}" class="px-5 py-3 rounded-xl text-white bg-teal-600 hover:bg-teal-700">Log
                out</a>
        {% else %}
            <a href="{% url 'core:login' %}" class="text-white hover:text-gray-200">Log in</a>

            <a href="{% url 'core:signup' %}" class="px-5 py-3 rounded-xl text-white bg-teal-600 hover:bg-teal-700">Sign
                up</a>
        {% endif %}
    </div>
</nav>

{% block content %}
{% endblock %}

{% block scripts %}
{% endblock %}
</body>
</html>

core/templates/core/frontpage.html
{% extends 'core/base.html' %}

{% block title %}Welcome | {% endblock %}

{% block content %}
<div class="p-10 lg:p-20 text-center">
    <h1 class="text-3xl lg:text-6xl text-white">Djangochat</h1>
</div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in | {% endblock %}

{% block content %}
<div class="p-10 lg:p-10 text-center">
    <h1 class="text-3xl lg:text-6xl text-white">Log in</h1>
</div>

<form method="post" action="." class="lg:w-1/4 px-4 mx-auto">
    {% csrf_token %}

    <div class="mb-5">
        <label class="text-white">Username</label>

        <input type="text" name="username" class="w-full mt-2 px-4 py-2 rounded-xl">
    </div>

    <div class="mb-5">
        <label class="text-white">Password</label>

        <input type="password" name="password" class="w-full mt-2 px-4 py-2 rounded-xl">
    </div>

    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %} 
                <div class="mb-5 p-4 rounded-xl bg-red-300 text-white">
                    <p>{{ error|escape }}</p>
                </div>
            {% endfor %}
        {% endfor %}
    {% endif %}

    <button class="px-5 py-3 rounded-xl text-white bg-teal-800 hover:bg-teal-700">Log in</button>
</form>
{% endblock %}

core/templates/core/signup.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="SignUp">
</form>
</body>
</html>

room/templates/room/room.html
{% extends 'core/base.html' %}

{% block title %}{{ room.name }} | {% endblock %}

{% block content %}
    <div class="p-10 lg:p-20 text-center">
        <h1 class="text-3xl lg:text-6xl text-white">{{ room.name }}</h1>
    </div>

    <div class="lg:w-2/4 mx-4 lg:mx-auto p-4 bg-white rounded-xl">
        <div class="chat-messages space-y-3" id="chat-messages">
            {% for message in messages %}
                <div class="p-4 bg-gray-200 rounded-xl">
                    <p class="font-semibold"> {{ message.user.username }} </p>
                    <p> {{ message.content }} </p>
                </div>

            {% empty %}
                <p>No Chat Yeat!</p>
            {% endfor %}
        </div>
    </div>

    <div class="lg:w-2/4 mt-6 mx-4 lg:mx-auto p-4 bg-white rounded-xl">
        <form method="post" action="." class="flex">
            {% csrf_token %}
            <input type="text" name="content" class="flex-1 mr-3" placeholder="Your message..." id="chat-message-input">

            <button
                    class="px-5 py-3 rounded-xl text-white bg-teal-600 hover:bg-teal-700"
                    id="chat-message-submit"
            >Submit
            </button>
        </form>
    </div>
{% endblock %}

{% block scripts %}
    {{ room.slug|json_script:"json-roomname" }}
    {{ request.user.username|json_script:"json-username" }}

    <script>
        const roomName = JSON.parse(document.getElementById('json-roomname').textContent);
        const userName = JSON.parse(document.getElementById('json-username').textContent);

        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/'
            + roomName
            + '/'
        );

        chatSocket.onmessage = function (e) {
            console.log('onmessage')

            const data = JSON.parse(e.data);

            if (data.message) {
                let html = '<div class="p-4 bg-gray-200 rounded-xl">';
                html += '<p class="font-semibold">' + data.username + '</p>';
                html += '<p>' + data.message + '</p></div>';

                document.querySelector('#chat-messages').innerHTML += html;

                scrollToBottom();

            } else {
                alert('The message was empty!');
            }
        }

        chatSocket.onclose = function (e) {
            console.log('onclose')
        }

        //

        document.querySelector('#chat-message-submit').onclick = function (e) {
            e.preventDefault();

            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;

            chatSocket.send(JSON.stringify({
                'message': message,
                'username': userName,
                'room': roomName
            }));
            messageInputDom.value = '';

            return false
        }

        //

        function scrollToBottom() {
            const objDiv = document.querySelector('#chat-messages');
            objDiv.scrollTop = objDiv.scrollHeight;
        }

        scrollToBottom();

    </script>
{% endblock %}

room/templates/room/rooms.html
{% extends 'core/base.html' %}

{% block title %}Rooms | {% endblock %}

{% block content %}
<div class="p-10 lg:p-20 text-center">
    <h1 class="text-3xl lg:text-6xl text-white">Rooms</h1>
</div>

<div class="w-full flex flex-wrap items-center">
    {% for room in rooms %}
        <div class="w-full lg:w-1/4 px-3 py-3">
            <div class="p-4 bg-white shadow rounded-xl text-center">
                <h2 class="mb-5 text-2xl font-semibold">{{ room.name }}</h2>

                <a href="{% url 'room:room' room.slug %}" class="px-5 py-3 block rounded-xl text-white bg-teal-600 hover:bg-teal-700">Join</a>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}